config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts, only: [:new, :create]
  get  '/posts/map', to: 'posts#map', as: 'map_posts'
  get 'posts/search', to: 'posts#search', as: 'posts_serach'

   # 例外
  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :img

  validates :content, presence: true, length: { maximum: 200 }
  validates :latitude, numericality: { in: 0..90 }
  validates :longitude, numericality: { in: 0..360 }
  validates :emoji, presence: true, length: { maximum: 1 }, format: { with: /[\u{10000}-\u{10FFFF}]/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  rescue_from ActiveRecord::RecordNotFound,   with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404

  def routing_error
    raise ActionController::RoutingError, params[:path]
  end

  private

  def render_404
    render 'error/404', status: :not_found
  end

end

app/controllers/posts/areas_controller.rb
class Posts::AreasController < ApplicationController

  def index
  end

  private
    def posts_params
      params.require(:post).permit(:latitude, :longitude)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(posts_params)
    @post.img_file_name = @post.img.key
    if @post.save
      flash[:success] = '投稿しました'
      redirect_to root_path
    else
      flash.now[:denger] = '投稿に失敗しました'
      render :new
    end
  end

  def map
  end

  def search
    current_lat = search_params[:latitude].to_f
    current_lng = search_params[:longitude].to_f
    @posts = Post.where( latitude:(current_lat - 0.009)..(current_lat + 0.009), longitude:(current_lng - 0.009)..(current_lng + 0.009) )

    render json: @posts
  end

  private

    def posts_params
      params.require(:post).permit(:latitude, :longitude, :content, :img, :emoji, :authenticity_token)
    end


    def search_params
      params.permit(:latitude, :longitude)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
 <% content_for :js do %>
   <%= javascript_import_module_tag "posts/index" %>
 <% end %>
<%= render "shared/header" %>
<div class="timeline">
  <h1 class="timeline-heading">現在地周辺の投稿</h1>
  <div class="timeline-address-wrapper">
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-map-pin-filled" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="none" fill="none" stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
      <path d="M18.364 4.636a9 9 0 0 1 .203 12.519l-.203 .21l-4.243 4.242a3 3 0 0 1 -4.097 .135l-.144 -.135l-4.244 -4.243a9 9 0 0 1 12.728 -12.728zm-6.364 3.364a3 3 0 1 0 0 6a3 3 0 0 0 0 -6z" stroke-width="0" fill="currentColor"></path>
    </svg>
    <div class="timeline-coords"> 京都府 中京区 </div>
  </div>
  <div id="post-list">
  </div>
</div>
<%= render "shared/new_post_button" %>
<%= render "shared/navbar", page: "list" %>
<style>
  .timeline-address-wrapper {
    position: sticky;
    top: 60px;
    display: flex;
    gap: 8px;
    align-items: center;
    color: var(--primary);
    background: white;
    padding: 6px 8px;
    z-index: 400;
    border-radius: 8px;
    background: #fff4e1;
    width: fit-content;
    margin-left: 16px;
    box-sizing: border-box;
    font-size: 14px;
  }
  
  .timeline-address-wrapper svg {
    width: 20px;
    height: 20px;
  }
  .timeline-coords {
    margin: 0;
  }
  .timeline-heading {
    font-size: 18px;
    padding: 16px;
  }
  #post-list {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }
  .post-list-notice {
    padding: 120px 0;
    text-align: center;
    font-size: 14px;
    color: gray;
  }
  .post-item {
    display: flex;
    gap: 16px;
    padding: 28px 24px;
    background-color: white;
    opacity: 0;
  }
  .post-item + .post-item {
    border-top: 1px solid #efefef;
  }
  .post-item:not(.loading) {
    animation: fadein-l2r 0.8s cubic-bezier(0, 0.75, 0.19, 1.69) forwards;
  }
  .post-item.loading {
    animation: loading-anm 1s infinite;
  }
  .post-content-emoji {
    font-size: 32px;
  }
  .loading .post-content-emoji {
    width: 40px;
    height: 40px;
    background: #e6e6e6;
    border-radius: 100%;
  }
  .post-item-rhs {
    display: flex;
    flex-grow: 1;
    flex-direction: column;
    gap: 12px
  }
  .post-item-header {
    display: flex;
    gap: 8px;
  }
  .post-content-date {
    font-size: 12px;
    color: gray;
    font-family: monospace;
  }
  .loading .post-content-date {
    background: #e6e6e6;
    border-radius: 8px;
    height: 16px;
    width: 100px;
  }
  .post-content-text {
    font-size: 14px;
    line-height: 1.2;
  }
  .loading .post-content-text {
    background: #e6e6e6;
    border-radius: 8px;
    height: 20px;
    width: 200px;
  }
  .post-image-container {
    max-width: 100%;
    max-height: 152px;
    box-sizing: border-box;
    display: flex;
    cursor: pointer;
  }
  .post-content-image {
    object-fit: contain;
    border-radius: 8px;
    max-height: 100%;
    max-width: 100%;
  }
  .post-content-coords {
    width: 100%;
    font-size: 10px;
    color: gray;
    text-align: right;
    text-decoration: none;
    display: flex;
    align-items: center;
    gap: 6px;
    justify-content: flex-end;
    font-family: monospace;
  }
  .post-content-coords svg {
    width: 16px;
    height: 16px;
  }

  .loading .post-content-coords {
    background: #e6e6e6;
    border-radius: 6px;
    height: 12px;
    width: 140px;
    align-self: flex-end;
  }

  @keyframes fadein-l2r {
    from {
      opacity: 0;
      transform: translateX(-24px);
    }
    to {
      opacity: 1;
      transform: translateX(0);
    }
  }

  @keyframes loading-anm {
    0% {
      opacity: 0.5;
    }
    50% {
      opacity: 1;
    }
    100% {
      opacity: 0.5;
    }
  }

</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.11.5/viewer.min.css" integrity="sha512-VysXDwG8m5Ngy43+b8+CdTe6Qkc69z8Oyxgo3yg8JqhRwwtjfSs+M4NEaP4As6l0ZCX+RpTyyuSiJnnO8JS5Eg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

app/views/posts/map.html.erb
<%= render "shared/header" %>
<div id="map" class="loading">
  <div class="map-loading-message-container">
    <svg class="map-loading-icon" xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-planet" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
      <path d="M18.816 13.58c2.292 2.138 3.546 4 3.092 4.9c-.745 1.46 -5.783 -.259 -11.255 -3.838c-5.47 -3.579 -9.304 -7.664 -8.56 -9.123c.464 -.91 2.926 -.444 5.803 .805"></path>
      <path d="M12 12m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"></path>
    </svg>
    <div class="map-loading-text">Loading</div>
  </div>
</div>
<%= render "shared/new_post_button" %>
<%= render "shared/navbar", page: "map" %>
<% content_for :js do %>
  <%= javascript_import_module_tag "posts/map" %>
<% end %>

<script>
  (g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})({
    key: "<%= ENV['GOOGLE_API_KEY'] %>",
    v: "weekly",
  });
</script>
<style>
  #map {
    width: 100%;
    height: calc(100vh - 61px - 73px);
  }
  #map.loading {
    animation: loading-anm 1s infinite;
    background: var(--light-gray);
  }
  .map-loading-message-container {
    display: flex;
    flex-direction: column;
    gap: 8px;
    width: 100%;
    height: 100%;
    align-items: center;
    justify-content: center;
  }
  .map-loading-text::after {
    content: "";
    animation: loading-dots 2s infinite;
  }
  .infowin-container {
    display: flex;
    gap: 12px
  }
  .infowin-rhs {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .infowin-content-emoji {
    font-size: 30px;
  }
  .infowin-content-text {
    font-size: 14px;
  }
  .infowin-image-container {
    max-height: 116px;
    max-width: 116px;
    box-sizing: border-box;
    display: flex;
    cursor: pointer;
  }
  .infowin-content-image {
    object-fit: contain;
    border-radius: 8px;
    height: 100%;
    width: 100%;
    object-fit: contain;
  }
  .infowin-content-date {
    color: gray;
    font-size: 12px;
  }

  @keyframes loading-anm {
    0% {
      opacity: 0.3;
    }
    50% {
      opacity: 1;
    }
    100% {
      opacity: 0.3;
    }
  }

  @keyframes loading-dots {
    0% {
      content: "";
    }
    25% {
      content: ".";
    }
    50% {
      content: "..";
    }
    75% {
      content: "...";
    }
  }
</style>

app/views/posts/new.html.erb
 <% content_for :js do %>
   <%= javascript_import_module_tag "posts/new" %>
 <% end %>
<div class="form-container">
  <%= form_with model: @post, data: {turbo: false } do |form| %>
    <div class="form-header">
      <div id="form-cancel-button">キャンセル</div>
      <span id="form-notice">位置情報を取得中...</span>
      <button id="form-submit-button" type="submit">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <path d="M10 14l11 -11"></path>
          <path d="M21 3l-6.5 18a.55 .55 0 0 1 -1 0l-3.5 -7l-7 -3.5a.55 .55 0 0 1 0 -1l18 -6.5"></path>
        </svg>
      </button>
    </div>
    <div class="form-main">
      <div class="form-icon">
        <div>
          <div class="form-emoji-wrapper">
            <div id="emoji-picker"></div>
            <div id="form-emoji"></div>
          </div>
        </div>
        <label for="customFileInput" class="custom-file-label" >
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-camera-plus" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M12 20h-7a2 2 0 0 1 -2 -2v-9a2 2 0 0 1 2 -2h1a2 2 0 0 0 2 -2a1 1 0 0 1 1 -1h6a1 1 0 0 1 1 1a2 2 0 0 0 2 2h1a2 2 0 0 1 2 2v3.5"></path>
            <path d="M16 19h6"></path>
            <path d="M19 16v6"></path>
            <path d="M9 13a3 3 0 1 0 6 0a3 3 0 0 0 -6 0"></path>
          </svg>
        </label>
      </div>
      <div class="form-message-wrapper">
        <div class="form-user-address">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-map-pin-filled" width="40" height="40" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M18.364 4.636a9 9 0 0 1 .203 12.519l-.203 .21l-4.243 4.242a3 3 0 0 1 -4.097 .135l-.144 -.135l-4.244 -4.243a9 9 0 0 1 12.728 -12.728zm-6.364 3.364a3 3 0 1 0 0 6a3 3 0 0 0 0 -6z" stroke-width="0" fill="currentColor"></path>
          </svg>
          京都府・中京区
        </div>
        <%= form.text_area :content, placeholder: "\"通りすがり\"の思い出を共有しよう。", id: "form-message" %>
        <%= form.file_field :img, class: 'custom-file-input', id: 'customFileInput', accept: 'image/*', style: 'display: none;' %>
      </div>
    </div>
    <%= form.hidden_field :longitude, id: "form-longitude", value: "" %>
    <%= form.hidden_field :latitude, id: "form-latitude", value: "" %>
    <%= form.hidden_field :emoji, id: "form-hidden-emoji", value: "" %>
    <%= form.file_field :img_file_name, class: 'custom-file-input', id: 'customFileInput', accept: 'image/*', style: 'display: none;' %>
  <% end %>
</div>
<style>
  .form-container {
    padding: 16px;
    height: 100vh;
    box-sizing: border-box;
  }
  .form-container > form {
    display: flex;
    flex-direction: column;
    gap: 8px;
    height: 100%;
  }
  .form-header {
    position: sticky;
    top: 0;
    display: flex;
    gap: 16px;
    align-items: center;
    justify-content: end;
    background-color: white;
  }
  #form-cancel-button {
    cursor: pointer;
    margin-right: auto;
    border: none;
    background: none;
    padding: 8px;
    border-radius: 12px;
    color: black;
    font-size: 12px;
  }
  #form-cancel-button:hover {
    text-decoration: underline;
  }
  #form-notice {
    font-size: 12px;
    color: gray;
    animation: loading-anm 1s infinite;
  }
  #form-submit-button {
    cursor: pointer;
    width: 40px;
    height: 40px;
    border-radius: 12px;
    display: grid;
    place-content: center;
    background: var(--primary);
    color: var(--white);
    border: none;
  }
  #form-submit-button[disabled] {
    background: var(--primary-dark);
    color: #dedede;
  }
  #form-submit-button svg {
    width: 100%;
    height: 100%;
  }

  .form-main{
    display: flex;
    gap: 8px;
    height: 100%;
  }
  .form-main > svg {
    color: gray;
    width: 44px;
    height: 44px;
  }
  .form-emoji-wrapper {
    position: relative;
  }
  #form-emoji {
    font-size: 40px;
    cursor: pointer;
    user-select: none;
  }
  #emoji-picker {
    position: absolute;
    top: 58px;
    display: none;
  }
  #emoji-picker.show {
    display: block;
  }
  .form-icon {
    display: flex;
    flex-direction: column;
    gap: 16px;
    align-items: center;
    padding: 0 12px 0 6px;
  }
  .form-message-wrapper {
    display: flex;
    flex-direction: column;
    gap: 12px;
    flex-grow: 1;
  }
  .form-user-address {
    display: flex;
    align-items: center;
    font-size: 14px;
    color: gray;
    padding: 4px 14px;
    background: #eeeeee;
    align-self: start;
    border-radius: 999px;
    font-weight: bold;
    margin-left: -4px;
  }
  .form-user-address svg {
    width: 20px;
    height: 20px;
    margin-right: 4px;
    animation: rotate 4s infinite;
  }
  #form-message {
    padding: 0px;
    resize: none;
    font-size: 1rem;
    width: 100%;
    box-sizing: border-box;
    flex-grow: 1;
    border: none !important;
    outline: none !important;
  }

  @keyframes loading-anm {
    0% {
      opacity: 0.5;
    }
    50% {
      opacity: 1;
    }
    100% {
      opacity: 0.5;
    }
  }

  @keyframes rotate {
    0% {
      transform: rotateY(0deg);
    }
    50% {
      transform: rotateY(180deg);
    }
    100% {
      transform: rotateY(360deg);
    }
  }
  .custom-file-label {
    cursor: pointer;
  }
  .custom-file-label svg {
    color: orange;
    width: 24px;
    height: 50px;
  }
  .custom-file-input {
    display: none;
  }
  .custom-file-input:checked + .custom-file-label {
    background-color: orange;
    color: white;
  }
}
#form-massage {
  max-height: 3em;
}
</style>

app/views/shared/_error_messages.html.erb
<%= @post.errors.full_messages %>
<% if @post.errors.any? %>
  <div>
    <%= @post.errors.full_messages %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class='flash-item alert alert-<%= message_type %>'>
    <%= message %>
    <svg class="flash-close-button" xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-x" width="40" height="40" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
      <path d="M18 6l-12 12"></path>
      <path d="M6 6l12 12"></path>
    </svg>
  </div>
<% end %>
<style>
  .flash-item {
    display: flex;
    align-items: center;
    gap: 12px;
    position: fixed;
    top: 16px;
    right: 16px;
    padding: 16px 18px;
    border-radius: 8px;
    z-index: 999;
    background: white;
    border: 1px solid #efefef;
    font-size: 14px;
  }
  .flash-item > svg {
    width: 22px;
    height: 22px;
    color: gray;
    cursor: pointer;
  }
</style>
<script>
  var flashCloseButton = document.querySelectorAll(".flash-close-button");

  if(flashCloseButton.length > 0){
    flashCloseButton.forEach((btn) => {
      btn.addEventListener("click", function() {
        var flashItem = btn.closest(".flash-item");
        flashItem.style.display = "none";
      });
    })
  }
</script>

app/views/shared/_header.html.erb
<header>
  <h1>
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-planet" width="40" height="40" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
      <path d="M18.816 13.58c2.292 2.138 3.546 4 3.092 4.9c-.745 1.46 -5.783 -.259 -11.255 -3.838c-5.47 -3.579 -9.304 -7.664 -8.56 -9.123c.464 -.91 2.926 -.444 5.803 .805"></path>
   <path d="M12 12m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"></path>
    </svg>
    通りすがりメモリー
  </h1>
</header>


<style>
  header {
    display: grid;
    position: sticky; 
    top: 4px;
    z-index: 900;
    padding: 12px;
    background-color: var(--primary) ;
    color: white; 
    text-align: center; 
    font-size: 10px;
    border-radius: 999px;
    width: 96%;
    margin: 0 auto 8px;
    box-sizing: border-box;
  }
  header svg {
    width: 26px;
    height: 26px;
  }
  header h1 {
    margin: 0;
    padding: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
  }
</style>

app/views/shared/_navbar.html.erb
<nav class="navbar-container">
  <%= link_to root_path, data: {turbo: false} do %>
    <div class="navbar-navitem <%= "active" if defined?(page) && page == "list" %>">
      <svg xmlns="http://www.w3.org/2000/svg" class="navbar-icon" width="40" height="40" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
        <path d="M9 6h11"></path>
        <path d="M12 12h8"></path>
        <path d="M15 18h5"></path>
        <path d="M5 6v.01"></path>
        <path d="M8 12v.01"></path>
        <path d="M11 18v.01"></path>
      </svg>
      リスト
    </div>
  <% end %>
  <%= link_to map_posts_path, data: {turbo: false } do %>
    <div class="navbar-navitem <%= "active" if defined?(page) && page == "map" %>">
      <svg xmlns="http://www.w3.org/2000/svg" class="navbar-icon" width="40" height="40" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
        <path d="M9 11a3 3 0 1 0 6 0a3 3 0 0 0 -6 0"></path>
        <path d="M17.657 16.657l-4.243 4.243a2 2 0 0 1 -2.827 0l-4.244 -4.243a8 8 0 1 1 11.314 0z"></path>
      </svg>
      マップ
    </div>
  <% end %>
</nav>
<style>
  .navbar-container {
    position: sticky;
    bottom: 0;
    width: 100%;
    height: 72px;
    display: flex;
    align-items: center;
    justify-content: space-evenly;
    backdrop-filter: blur(10px);
    background: transparent;
    border-top: 1px solid #efefef;
  }

  .navbar-container > a {
    text-decoration: none !important;
  }

  .navbar-navitem {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 16px;
    cursor: pointer;
    transition: 0.2s;
    color: gray;
    border-radius: 999px;
    padding: 12px 18px;
  }
  .navbar-navitem.active {
    font-weight: bold;
    background: #0000000a;
    color: #242424;
  }
  .navbar-navitem:hover {
    box-shadow: inset 0 0 0 2px #f0f0f0;
    transform: scale(1.04);
    color: black;
  }

  .navbar-icon {
    width: 24px;
    height: 24px;
  }
</style>

app/views/shared/_new_post_button.html.erb
<%= link_to new_post_path, class:"create-post-button" do %>
  <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-message-chatbot" width="40" height="40" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
    <path d="M4 21v-13a3 3 0 0 1 3 -3h10a3 3 0 0 1 3 3v6a3 3 0 0 1 -3 3h-9l-4 4"></path>
    <path d="M9.5 9h.01"></path>
    <path d="M14.5 9h.01"></path>
    <path d="M9.5 13a3.5 3.5 0 0 0 5 0"></path>
  </svg>
<% end %>
<style>
  .create-post-button {
    width: 54px;
    height: 54px;
    border-radius: 100%;
    position: fixed;
    bottom: 66px;
    right: 16px;
    background: var(--primary);
    display: grid;
    place-content: center;
    color: var(--white);
    z-index: 999;
    box-shadow: 0 2px 8px 1px rgba(0, 0, 0, 0.16);
  }
  .create-post-button svg {
    width: 34px;
    height: 34px;
  }
</style>